server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters:
            - StripPrefix=1
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription-service/**
          filters:
            - StripPrefix=1
        - id: interaction-service
          uri: lb://interaction-service
          predicates:
            - Path=/interaction-service/**
          filters:
            - StripPrefix=1
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/media-service/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  tracing:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka