spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:29092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9002

server:
  port: 8080